[package]
name = "wgpu-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pollster = "0.2.5"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
wgpu = "0.13.1"
winit = "0.27.3"
